[package]
name = "sketch"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.12.0"
bevy = "0.13.2"

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

[profile.release]
opt-level = 'z'
